

WoW % = 
VAR CW = [Current Metric]
VAR PW= CALCULATE ( [Current Metric], DATEADD('Date'[Date] ,-7,day)) 
VAR WOW = CW - PW
RETURN 
   DIVIDE( WOW, PW)
***************************************************************************
Venues = count(Venues[VenueKey])
***************************************************************************
USERPRINCIPALNAME = USERPRINCIPALNAME()
***************************************************************************
= IF( SUM(InternetSales_USD[SalesAmount_USD])= 0   , BLANK()   , SUM(ResellerSales_USD[SalesAmount_USD])/SUM(InternetSales_USD[SalesAmount_USD])   ) 
***************************************************************************
Average Bet = IF([Gaming Turnover]==0, 0 ,
 [Gaming Turnover] / CONVERT( [Games Played],CURRENCY))
***************************************************************************
MaxStrokes = LOOKUPVALUE(OpeningHours[MaximumDailyGamesPlayedPerEGM],OpeningHours[VenueKey],Meters[VenueKey],OpeningHours[DayOfWeekKey],related('Day Of Week'[dayOfWeekKey]))
***************************************************************************
let
    Source = Sql.Database(SERVER, PortfolioDB, [Query="exec PBI.GetPOSTargets '" & PortfolioId & "', '" &UserID& "', '" & Secret & "'"]),
    #"Added Custom" = Table.AddColumn(Source, "POSSalesTarget", each [BarSalesTarget] + [FoodSalesTarget] + [RetailSalesTarget])
in
    #"Added Custom"
***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************

***************************************************************************